#!/usr/bin/env bash

set -euo pipefail
export DOTFILES_PATH="$HOME/_dotfiles"

# Pretty print function
pp() {
    local symbol=$1
    local message=$2
    printf "\033[1m%s\033[0m %s\n" "$symbol" "$message"
}

pp "→" "Starting setup..."

handle_midway_auth() {
    set +e
    mwinit
    local status=$?
    set -e
    
    if [ $status -ne 0 ]; then
        pp "×" "Authentication failed"
        exit 1
    fi
}

if command -v mwinit &>/dev/null; then
    AUTH_RESPONSE=$(curl -s -b ~/.midway/cookie -c ~/.midway/cookie https://midway-auth.amazon.com/api/session-status)
    
    if ! echo "$AUTH_RESPONSE" | grep -q '"authenticated":true'; then
        pp "!" "Refreshing credentials..."
        handle_midway_auth
    else
        EXPIRES_AT=$(echo "$AUTH_RESPONSE" | grep -o '"expires_at":[0-9]*' | cut -d':' -f2)
        CURRENT_TIME=$(date +%s)
        TIME_REMAINING=$((EXPIRES_AT - CURRENT_TIME))
        
        if [ "$TIME_REMAINING" -lt 3600 ]; then
            pp "!" "Credentials expiring soon, refreshing..."
            handle_midway_auth
        fi
    fi
fi

pp "→" "Preparing installation"

# Check for git
if ! command -v git &>/dev/null; then
    pp "×" "Git is required but not installed"
    exit 1
fi

if ! command -v brew &>/dev/null; then
  pp "!" "Hombrew Not found, installing..."
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"  &>/dev/null;
  # Add Homebrew to PATH for this session
  if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"  &>/dev/null
  elif [[ -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"  &>/dev/null
  elif [[ -f /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"  &>/dev/null
  fi
  pp "✓" "Homebrew installed"
fi

if ! command -v gum &>/dev/null; then
  pp "!" "Gum not found. Installing via Homebrew..."
  eval "(brew install gum)" &>/dev/null
  pp "✓" "gum is installed"
fi

if [ -d "$DOTFILES_PATH" ]; then
  pp "!" "${DOTFILES_PATH} exists..Deleting"
  rm -rf "$DOTFILES_PATH"
fi


# Clone repository
pp "→" "Cloning dotfiles..."
git clone --quiet --no-progress --depth 1 https://github.com/vinodismyname/dotfiles-v.git "$DOTFILES_PATH" &>/dev/null || {
    pp "×" "Failed to clone repository"
    exit 1
}

# Make scripts executable
find "$DOTFILES_PATH" -type f \( -name "*.sh" -o -name "*.bash" -o -name "*.zsh" \) -exec chmod +x {} +

# Run installer
pp "→" "Running installer..."
"$DOTFILES_PATH/main/install"